### ISSUE TITLE
Quest feature is broken

### ISSUE THREAD

**Issue by pirwen** [SyndroneOnline/SyndroneOnline.com#15]
Hopé we can fix it so we can work on some more quests ^^

**Comment by emiliobool** [comment]
https://www.dropbox.com/s/tu8zgaqtg3phxix/Screenshot%202016-10-08%2018.32.12.png?dl=0

not adding this as a new issue yet since I don't know about the future of the quest system, so the overlay shows that empty block since the dialog is reused

it is supposed to show the rewards but that data isn't sent or set so the proper solution would be to hide it, but that's the reason I'm not adding it as a new issue, it would imply modifying it on every single part where the code was copied...

**Comment by emiliobool** [comment]
I think the quest feature is working? I'll close for now
